[package]
name = "reqs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full", "time"] }
futures = "0.3"
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
