# The URL the site will be built for
base_url = "https://reqs.hahwul.com"
title = "Reqs"
theme = "goyo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
bottom_footnotes = true

[extra]
logo_text = "Reqs"
logo_image_path = "images/logo.png"
default_thumbnail = "images/preview.jpg"
twitter_site = "@hahwul"
twitter_creator = "@hahwul"

nav = [
    { name = "Documents", url = "/get_started/installation", type = "url", icon = "fa-solid fa-book" },
    { name = "GitHub", url = "https://github.com/hahwul/reqs", type = "url", icon = "fa-brands fa-github" },
    { name = "Links", type = "dropdown", icon = "fa-solid fa-link", members = [
        { name = "Crates", url = "https://crates.io/crates/reqs", type = "url", icon = "fa-solid fa-box" },
        { name = "Creator Blog", url = "https://www.hahwul.com", type = "url", icon = "fa-solid fa-fire-flame-curved" },
    ] },
]
